- name: Sign in to Azure 
# Use the GitHub secret you added.
- uses: azure/login@v1
  with:
    creds: ${{ secrets.AZURE_CREDENTIALS }}
- name: Deploy to Azure Web App
# Remove publish-profile.
- uses: azure/webapps-deploy@v2
  with:
    app-name: 'powerforce'
    slot-name: 'production'
    package: .
- name: Sign out of Azure.
  run: |
    az logout
